### ISSUE TITLE
receive HTTP::NET `read_nonblock': end of file reached (EOFError) error when running dandelion deploy

### ISSUE THREAD

**Issue by eggmatters** [dandelion/dandelion#107]
I receive the following error when attempting to run `dandelion --config=dandelion-live.yml deploy`:

``` bash
Connecting to ftp://myuser@my.ip.01//my_path/my_folder
/usr/lib/ruby/2.1.0/net/protocol.rb:153:in `read_nonblock': end of file reached (EOFError)
    from /usr/lib/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
    from /usr/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:1111:in `readline'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:290:in `getline'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:301:in `getmultiline'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:319:in `getresp'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:339:in `voidresp'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:362:in `block in voidcmd'
    from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:360:in `voidcmd'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:376:in `sendport'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:387:in `makeport'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:422:in `transfercmd'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:488:in `block (2 levels) in retrbinary'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:199:in `with_binary'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:486:in `block in retrbinary'
    from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:485:in `retrbinary'
    from /usr/lib/ruby/2.1.0/net/ftp.rb:618:in `getbinaryfile'
    from /var/lib/gems/2.1.0/gems/dandelion-0.4.15/lib/dandelion/adapter/ftp.rb:22:in `read'
    from /var/lib/gems/2.1.0/gems/dandelion-0.4.15/lib/dandelion/workspace.rb:74:in `remote_sha'
    from /var/lib/gems/2.1.0/gems/dandelion-0.4.15/lib/dandelion/workspace.rb:33:in `remote_commit'
    from /var/lib/gems/2.1.0/gems/dandelion-0.4.15/lib/dandelion/command/deploy.rb:25:in `execute!'
    from /var/lib/gems/2.1.0/gems/dandelion-0.4.15/lib/dandelion/cli.rb:73:in `execute!'
    from /var/lib/gems/2.1.0/gems/dandelion-0.4.15/bin/dandelion:8:in `<top (required)>'
    from /usr/local/bin/dandelion:23:in `load'
    from /usr/local/bin/dandelion:23:in `<main>'
```

My config file `dandelion-live.yml` looks like:

``` yml
scheme: ftp
host: my.ip.01
username: myuser
password: mypasswd
path: /my_path/my_folder
exclude:
    - .gitignore
    - dandelion.yml
    - dandelion-live.yml
    - .bowerrc
    - .sass-cache
    - client_provided
    - node_modules
    - .gitattributes
    - bower.json
    - config.rb
    - Gruntfile.js
    - package.json
    - phpunit.xml
    - README.md
    - server.php
    - '*.iml'
    - vendor/bin/boris
    - vendor/bin/classpreloader.php
    - .htaccess
revision_file: .revision
execute_before:
  - ls
```
